import 'package:flutter/material.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2443Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedKondisiBekasWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedSimiliarProductWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2277Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2439Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedKomentarWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedBeratSatuan15KgWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedCanonFTLensaCanon55mmf12bawaanoriginalKondisifisikbodym.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedStarWidget5.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedBarangsesuaifotonominussemogaawetWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRP2200000Widget1.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedSpesifikasiWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2445Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRectangle1534Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2452Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedTokoelektronikpsWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRectangle1517Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedKategoriKameraFilmWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2444Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedCanonFTlensCanon55mmf112analogWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedReviewWidget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRectangle1515Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedRectangle1535Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedGroup2449Widget.dart';
import 'package:flutterapp/mobile1app/generatedtopicwidget/generated/GeneratedEtalaseSemuaEtalaseWidget.dart';

/* Frame topic
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTopicWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1155.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 360.0,
                            height: 1155.0,
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(30.0),
                            ),
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.circular(30.0),
                                    child: Container(
                                      color: Color.fromARGB(255, 247, 247, 247),
                                    ),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 66.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 197.0,
                                    child: GeneratedRectangle1535Widget(),
                                  ),
                                  Positioned(
                                    left: 27.0,
                                    top: 946.0,
                                    right: null,
                                    bottom: null,
                                    width: 94.53081512451172,
                                    height: 138.5641632080078,
                                    child: GeneratedGroup2443Widget(),
                                  ),
                                  Positioned(
                                    left: 133.0,
                                    top: 946.0,
                                    right: null,
                                    bottom: null,
                                    width: 93.53081512451172,
                                    height: 138.5641632080078,
                                    child: GeneratedGroup2444Widget(),
                                  ),
                                  Positioned(
                                    left: 239.1746826171875,
                                    top: 946.0,
                                    right: null,
                                    bottom: null,
                                    width: 93.53081512451172,
                                    height: 138.5641632080078,
                                    child: GeneratedGroup2445Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: null,
                                    bottom: null,
                                    width: 360.0,
                                    height: 55.0,
                                    child: GeneratedGroup2439Widget(),
                                  ),
                                  Positioned(
                                    left: 105.0,
                                    top: 75.0,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 150.0,
                                    child: GeneratedRectangle2Widget1(),
                                  ),
                                  Positioned(
                                    left: 105.0,
                                    top: 75.0,
                                    right: null,
                                    bottom: null,
                                    width: 150.0,
                                    height: 150.0,
                                    child: GeneratedGroup2277Widget(),
                                  ),
                                  Positioned(
                                    left: 133.0,
                                    top: 231.0,
                                    right: null,
                                    bottom: null,
                                    width: 92.00003814697266,
                                    height: 25.70587921142578,
                                    child: GeneratedGroup12Widget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 271.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 104.0,
                                    child: GeneratedRectangle35Widget(),
                                  ),
                                  Positioned(
                                    left: 65.0,
                                    top: 286.0,
                                    right: null,
                                    bottom: null,
                                    width: 232.0,
                                    height: 17.0,
                                    child:
                                        GeneratedCanonFTlensCanon55mmf112analogWidget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 390.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 194.0,
                                    child: GeneratedRectangle1515Widget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 714.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 194.0,
                                    child: GeneratedRectangle1517Widget(),
                                  ),
                                  Positioned(
                                    left: 47.0,
                                    top: 748.0,
                                    right: null,
                                    bottom: null,
                                    width: 70.0,
                                    height: 39.10874938964844,
                                    child: GeneratedKomentarWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 397.0,
                                    right: null,
                                    bottom: null,
                                    width: 86.0,
                                    height: 23.0,
                                    child: GeneratedSpesifikasiWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 722.0,
                                    right: null,
                                    bottom: null,
                                    width: 58.0,
                                    height: 23.0,
                                    child: GeneratedReviewWidget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 923.0,
                                    right: null,
                                    bottom: null,
                                    width: 119.0,
                                    height: 20.0,
                                    child: GeneratedSimiliarProductWidget(),
                                  ),
                                  Positioned(
                                    left: 30.0,
                                    top: 599.0,
                                    right: null,
                                    bottom: null,
                                    width: 300.0,
                                    height: 100.0,
                                    child: GeneratedRectangle1534Widget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 616.0,
                                    right: null,
                                    bottom: null,
                                    width: 65.0,
                                    height: 65.0,
                                    child: GeneratedEllipse9Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.1774136225382487;

                                      final double height =
                                          constraints.maxHeight *
                                              0.0071285033122801674;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.3333333333333333,
                                            y: constraints.maxHeight *
                                                0.5722943722943723,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: GeneratedStarWidget5(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 135.0,
                                    top: 345.0,
                                    right: null,
                                    bottom: null,
                                    width: 92.0,
                                    height: 18.0,
                                    child: GeneratedRP2200000Widget1(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 423.0,
                                    right: null,
                                    bottom: null,
                                    width: 75.0,
                                    height: 14.0,
                                    child: GeneratedKondisiBekasWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 436.0,
                                    right: null,
                                    bottom: null,
                                    width: 101.0,
                                    height: 14.0,
                                    child: GeneratedBeratSatuan15KgWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 449.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 14.0,
                                    child: GeneratedKategoriKameraFilmWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 462.0,
                                    right: null,
                                    bottom: null,
                                    width: 116.0,
                                    height: 14.0,
                                    child: GeneratedEtalaseSemuaEtalaseWidget(),
                                  ),
                                  Positioned(
                                    left: 120.0,
                                    top: 630.0,
                                    right: null,
                                    bottom: null,
                                    width: 110.0,
                                    height: 17.0,
                                    child: GeneratedTokoelektronikpsWidget(),
                                  ),
                                  Positioned(
                                    left: 43.0,
                                    top: 479.0,
                                    right: null,
                                    bottom: null,
                                    width: 246.0,
                                    height: 98.0,
                                    child:
                                        GeneratedCanonFTLensaCanon55mmf12bawaanoriginalKondisifisikbodym(),
                                  ),
                                  Positioned(
                                    left: 47.0,
                                    top: 790.0,
                                    right: null,
                                    bottom: null,
                                    width: 211.0,
                                    height: 14.0,
                                    child:
                                        GeneratedBarangsesuaifotonominussemogaawetWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.6234724256727431;

                                      final double height =
                                          constraints.maxHeight *
                                              0.009595238491570278;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth *
                                                0.2777777777777778,
                                            y: constraints.maxHeight *
                                                0.825974025974026,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: GeneratedGroup2452Widget(),
                                            ))
                                      ]);
                                    }),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: null,
              top: null,
              right: 0.0,
              bottom: 0.0,
              width: 225.0,
              height: 37.0,
              child: GeneratedGroup2449Widget(),
            )
          ]),
    ));
  }
}
